---
title: "G4 CUT&Tag analysis mESC (ERCC WT and KO)"
output: html_notebook
---

Simon Elsässer, Karolinska Institutet (2023)

### Profile plots of promoters, enhancders and significant peaks determined by DESeq2.

```{r fig.width=6, fig.height=3}
bw_dir <- "../bigwig"

library("wigglescout")
library("ggpubr")
library("ggplot2")
library("DESeq2")
library("dplyr")
library("ggrastr")

clean <- function (fn) {
  fn <- gsub(pattern = ".+/", "", x = fn)
  fn <- gsub(pattern = "_R", " ", x = fn)
  fn <- gsub(pattern = ".mm39.+", "", x = fn)
  fn <- gsub(pattern = ".bw", "", x = fn)
  fn <- gsub(pattern = ".combined", "", x = fn)
  fn <- gsub(pattern = ".+_CnT_", "", x = fn)
  fn <- gsub(pattern = "ERCC", "", x = fn)
  fn <- gsub(pattern = "_batch2", "", x = fn)
  fn <- gsub(pattern = "-", " ", x = fn)
  fn <- gsub(pattern = "_", " ", x = fn)
  fn <- gsub(pattern = " HA ", " ", x = fn)
  fn <- gsub(pattern = "D1D6", "FANCJ-/-", x = fn)
  fn <- gsub(pattern = "P2D2", "DHX36-/-", x = fn)
  fn <- gsub(pattern = "P3D4", "FANCJ-/-DHX36-/-", x = fn)
  return(fn)
}

theme_blank <- theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank())

G4.BWs <- list.files(bw_dir,pattern="G4_CnT_ERCC.+_rep..bw",full.names = T)
R.BWs <- list.files(bw_dir,pattern="Rloop_CnT_ERCC.+_rep..bw",full.names = T)

mypal <-c("cornflowerblue","orange","red2","#505050")
mypal2 <-c("darkorange2","darkorange2","#505050","#505050")
```

## DJ peaks
```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
plot_profile_G4_DJ <- plot_bw_profile(bwfiles = G4.BWs,loci = "../peaks/G4_CnT_combined_peaks_DJ.bed", mode="center", labels = clean(G4.BWs),show_error=T,colors = mypal2, verbose=F) + scale_y_continuous(limits=c(0,12))
plot_profile_G4_DJ$labels$title <- "G4 CnT"
plot_profile_G4_DJ
```

## non-DJ peaks
```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
plot_profile_G4_nonDJ <- plot_bw_profile(bwfiles = G4.BWs,loci = "../peaks/G4_CnT_combined_peaks_nonDJ.bed", mode="center", labels = clean(G4.BWs),show_error=T,colors = mypal2, verbose=F) + scale_y_continuous(limits=c(0,12))
plot_profile_G4_nonDJ$labels$title <- "G4 CnT"
plot_profile_G4_nonDJ
```

## replicate consistency
```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
df <- data.frame(bw_loci(G4.BWs,loci="../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed"))
ggscatter(df,"G4_CnT_ERCCWT_rep1","G4_CnT_ERCCWT_rep2") + geom_abline(a=0,b=1,linetype = "dotted")
```

## ERCC KO vs WT
```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
df$WT <- (df$G4_CnT_ERCCWT_rep1+df$G4_CnT_ERCCWT_rep2)/2
df$KO <- (df$G4_CnT_ERCCKO_rep1+df$G4_CnT_ERCCKO_rep2)/2

df$lg2fc <- log((df$KO+1)/(df$WT+1),2)
df$lg2WT <- log(df$WT,2)

ggscatter(df[df$WT<100,],"WT","lg2fc",size=0.5,alpha=0.2,add="loess",add.params=list(color="orange")) + geom_hline(yintercept = 0,linetype = "dotted",color="orange") + stat_summary_bin(fun.y="mean",bins=20,color="orange")
```
## replicate consistency
```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
rdf <- data.frame(bw_loci(R.BWs,loci="../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed"))
ggscatter(rdf[rdf$Rloop_CnT_ERCCWT_rep1<500,],"Rloop_CnT_ERCCWT_rep1","Rloop_CnT_ERCCWT_rep2") + geom_abline(a=0,b=1,linetype = "dotted")
```

## ERCC KO vs WT
```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
rdf$WT <- (rdf$Rloop_CnT_ERCCWT_rep1+rdf$Rloop_CnT_ERCCWT_rep2)/2
rdf$KO <- (rdf$Rloop_CnT_ERCCKO_rep1+rdf$Rloop_CnT_ERCCKO_rep2)/2

rdf$lg2fc <- log((rdf$KO+1)/(rdf$WT+1),2)
rdf$lg2WT <- log(rdf$WT,2)

ggscatter(rdf[rdf$WT<100,],"WT","lg2fc",size=0.5,alpha=0.2,add="loess",add.params=list(color="orange")) + geom_hline(yintercept = 0,linetype = "dotted",color="orange") + stat_summary_bin(fun.y="mean",bins=20,color="orange")
```


```{r fig.width=9, fig.height=6, error=F,echo=F,prompt=F,warning=F}
sort_v <- bw_heatmap(bwfiles = G4.BWs[3],loci = "../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed",mode="center")[[1]]
sort_o <- order(rowMeans(sort_v) + score(rtracklayer::import("../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed"))*1000)

h1 <- plot_bw_heatmap(G4.BWs[3],"../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed",mode="center",order_by=sort_o,max_rows_allowed = 200,verbose=F, zmax = 21)
h2 <- plot_bw_heatmap(G4.BWs[1],"../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed",mode="center",order_by=sort_o,max_rows_allowed = 200,verbose=F, zmax = 21)
h3 <- plot_bw_heatmap(R.BWs[3],"../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed",mode="center",order_by=sort_o,max_rows_allowed = 200,verbose=F, zmax = 30)
h4 <- plot_bw_heatmap(R.BWs[1],"../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed",mode="center",order_by=sort_o,max_rows_allowed = 200,verbose=F, zmax = 30)

h5 <- plot_bw_heatmap(paste0(bw_dir,"PQS_scores.mm39.bw"),"../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed",mode="center",order_by=sort_o,max_rows_allowed = 200,verbose=F,zmin=2, zmax = 10)

p <- ggarrange(h1,h2,h3,h4, ncol = 4,common.legend = T)
ggsave('panels/heatmaps_G4_Rloop_ERCC.pdf',p)
p
```
```{r fig.width=7, fig.height=6, error=F,echo=F,prompt=F,warning=F}
sort_v <- bw_heatmap(bwfiles = G4.BWs[3],loci = "../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed",mode="center")[[1]]
sort_o <- order(rowMeans(sort_v) + score(import("../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed"))*1000)

d1 <- plot_bw_heatmap(G4.BWs[1],bg_bwfile = G4.BWs[3],"../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed",mode="center",order_by=sort_o,max_rows_allowed = 200,verbose=F,norm_mode = "log2fc")
d2 <- plot_bw_heatmap(R.BWs[1],bg_bwfile = R.BWs[3],"../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed",mode="center",order_by=sort_o,max_rows_allowed = 200,verbose=F,norm_mode = "log2fc")

p <- ggarrange(d1,d2, ncol = 2,common.legend = F)
ggsave('panels/heatmaps_G4_Rloop_ERCC_diff.pdf',p)
p
```



## top DKO peaks
```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
plot_profile_G4_DKO_top <- plot_bw_profile(bwfiles = G4.BWs,loci = "../peaks/G4_CnT_combined_peaks_DESeq_DKO_sig_lfc_base_cutoff.bed", mode="center", labels = clean(G4.BWs),show_error=T,colors = mypal2, verbose=F) + scale_y_continuous(limits=c(0,13))
plot_profile_G4_DKO_top
```
## FANCJ diff peaks
```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
plot_profile_G4_FANCJ <- plot_bw_profile(bwfiles = G4.BWs,loci = "../peaks/G4_CnT_combined_peaks_DESeq_FANCJ_sig.bed", mode="center", labels = clean(G4.BWs),show_error=T,colors = mypal2, verbose=F) + scale_y_continuous(limits=c(0,13))
plot_profile_G4_FANCJ
```

```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
plot_profile_G4_TSShi <- plot_bw_profile(bwfiles = G4.BWs,loci = "../genome/genes_hi_lt10kb.mm39.bed", mode="start", labels = clean(G4.BWs),show_error=T,colors = mypal2, verbose=F) + scale_y_continuous(limits=c(0,30))
plot_profile_G4_TSShi
```
```{r fig.width=6, fig.height=4}
comb.BWs <- paste0(bw_dir,c("G4_CnT_ERCC_WT_combined.bw","G4_CnT_ERCC_KO_combined.bw"))

df <- as.data.frame(bw_loci(comb.BWs,loci="../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed",labels=clean(comb.BWs)))

df$lfc <- log2((df$KO+1)/(df$WT+1))
df <- df[rowSums(df[,6:7]) < 200,]

mdf <- reshape2::melt(df[,6:8])
mdf$variable <- sub("ERCC.","",mdf$variable)
p <- ggviolin(mdf, x="variable",y="value",fill="variable",palette = mypal2[c(3,1)], add="mean_sd", title = "G4 ERCC1 KO vs WT")
facet(p, facet.by = "name", ncol=6) + coord_cartesian(ylim=c(0,30)) + stat_compare_means(label.y = 30, aes(label = paste0("p=", after_stat(p.format))))
```

# R loops

## Rloops DJ

```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
plot_profile_Rloop_DJ <- plot_bw_profile(bwfiles = R.BWs,loci = "../peaks/G4_CnT_combined_peaks_DJ.bed", mode="center", labels = clean(R.BWs),show_error=T,colors = mypal2, verbose=F) + scale_y_continuous(limits=c(0,27))
plot_profile_Rloop_DJ$labels$title <- "R-loop CnT"
plot_profile_Rloop_DJ
```

## Rloops nonDJ
```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
plot_profile_Rloop_nonDJ <- plot_bw_profile(bwfiles = R.BWs,loci = "../peaks/G4_CnT_combined_peaks_nonDJ.bed", mode="center", labels = clean(R.BWs),show_error=T,colors = mypal2, verbose=F) + scale_y_continuous(limits=c(0,28))
plot_profile_Rloop_nonDJ$labels$title <- "R-loop CnT"
plot_profile_Rloop_nonDJ
```

## Rloops FANCJ
```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
plot_profile_Rloop_FANCJ <- plot_bw_profile(bwfiles = R.BWs,loci = "../peaks/G4_CnT_combined_peaks_DESeq_FANCJ_sig.bed", mode="center", labels = clean(R.BWs),show_error=T,colors = mypal2, verbose=F)
plot_profile_Rloop_FANCJ
```
```{r fig.width=6, fig.height=4}
comb.BWs <- paste0(bw_dir,c("Rloop_CnT_ERCC_WT_combined.bw","Rloop_CnT_ERCC_KO_combined.bw"))

df <- as.data.frame(bw_loci(comb.BWs,loci="../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed",labels=clean(comb.BWs)))

df$lfc <- log2((df$KO+1)/(df$WT+1))
df <- df[rowSums(df[,6:7]) < 200,]

mdf <- reshape2::melt(df[,6:8])
mdf$variable <- sub("ERCC.","",mdf$variable)
p2 <- ggviolin(mdf, x="variable",y="value",fill="variable",palette = mypal2[c(3,1)], add="mean_sd", title = "R-loop ERCC1 KO vs WT")
facet(p2, facet.by = "name", ncol=6) + coord_cartesian(ylim=c(0,50)) + stat_compare_means(label.y = 45, aes(label = paste0("p=", after_stat(p.format))))
```


```{r fig.width=7, fig.height=7}
library(cowplot)

p <- ggdraw() +
  draw_plot(plot_profile_G4_DJ, x = 0, y = .5, width = .5, height = .5) +
  draw_plot(plot_profile_G4_nonDJ, x = 0.5, y = .5, width = .5, height = .5) +
  draw_plot(plot_profile_Rloop_DJ, x = 0, y = 0, width = .5, height = .5) +
  draw_plot(plot_profile_Rloop_nonDJ, x = .5, y = 0, width = .5, height = .5) +

  draw_plot_label(label = c("a", "b", "c","d"), size = 15,
                  x = c(0, .5, 0, .5), y = c(1, 1, .5, .5))
ggsave('panels/panel_G4_Rloop_ERCCKO.pdf',p)
p
```
