---
title: "G4 CUT&Tag analysis mESC (WT, FANCJ KO, DHX36 KO, DKO)"
output: html_notebook
---

Simon Elsässer, Karolinska Institutet (2023)

### Comparison DJ (DKO) vs non-DJ peaks (non-sig) from DESeq2.

```{r fig.width=6, fig.height=3}
bw_dir <- "../bigwig"

library("wigglescout")
library("ggpubr")
library("ggplot2")
library("DESeq2")
library("dplyr")
library("ggrastr")
library("reshape2")
library("effsize")
library("gtools")

clean <- function (fn) {
  fn <- gsub(pattern = ".+/", "", x = fn)
  fn <- gsub(pattern = ".mm9.+", "", x = fn)
  fn <- gsub(pattern = ".mm39.+", "", x = fn)
  fn <- gsub(pattern = "_S.+", "", x = fn)
  fn <- gsub(pattern = "_combined", "", x = fn)
  fn <- gsub(pattern = "G4_CnT_", "", x = fn)
  fn <- gsub(pattern = "_batch2", "", x = fn)
  fn <- gsub(pattern = "-", "", x = fn)
  fn <- gsub(pattern = "_", "", x = fn)
  fn <- gsub(pattern = " HA ", " ", x = fn)
  fn <- gsub(pattern = "D1D6", "FANCJ", x = fn)
  fn <- gsub(pattern = "P2D2", "DHX36", x = fn)
  fn <- gsub(pattern = "P3D4", "DKO", x = fn)
  return(fn)
}

BWs <- list.files(bw_dir,pattern="G4_CnT_[DPW].+_combined.bw",full.names = T)

mypal <-c("cornflowerblue","orange","red2","#505050")
mypal3 <-c("cornflowerblue","cornflowerblue","cornflowerblue","orange","orange","orange","red2","red","red2","black","black","black")
mypal2 <-c("cornflowerblue","cornflowerblue","orange","orange","red2","red","black","black")
```

## DHX36-/- vs WT significant peaks
```{r fig.width=3, fig.height=3, error=F,echo=F,prompt=F,warning=F}
DJ <- rtracklayer::import("../peaks/G4_CnT_combined_peaks_DJ_nonDJ.bed")
pks <- rtracklayer::import("../peaks/G4_CnT_combined_peaks_DESeq_sig_categories.bed")
pks_DJ <- bedscout::annotate_overlapping_features(pks,feat_gr = DJ,name_field = "name")
pks_DJ$nearby_features[is.na(pks_DJ$nearby_features)] <- ""
table(pks_DJ$name)
table(pks_DJ$name,pks_DJ$nearby_features)
table(pks_DJ$nearby_features)
```
```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
mypal <-c("red2","#505050")
df <- as.data.frame(bw_loci(BWs,pks_DJ)) 
colnames(df)<-clean(colnames(df))
df$DJ <- pks_DJ$nearby_features
mdf <- melt(df[,8:11])
mdf<-mdf[mdf$DJ!="",]

ggviolin(mdf,x="variable",y="value",fill="variable",add="mean",palette = mypal,facet.by = "DJ") +  stat_compare_means(method = "t.test",label.y = 60) + coord_cartesian(ylim=c(0,70))
```

```{r}
mdf <- melt(df[df$DJ=="DJ",8:11])
cohen.d(mdf$value,mdf$variable)

mdf <- melt(df[df$DJ=="nonDJ",8:11])
cohen.d(mdf$value,mdf$variable)
```
```{r}
ggviolin(mdf,x="DJ",y="value",fill="DJ",add="mean",palette = c("#505050","#505050"),facet.by = "variable") +  stat_compare_means(label.y = 60) + coord_cartesian(ylim=c(0,70))
ggsave('plots/violin_G4_WT_signal_DJ_wilcoxon.pdf')
```
```{r}
df1 <- df[df$DJ!="",]
cohen.d(df1$WT,df1$DJ)
cohen.d(df1$DKO,df1$DJ)
```

```{r fig.width=3, fig.height=3, error=F,echo=F,prompt=F,warning=F}
mypal <-c("#505050","red2","#505050","#505050","#505050")

df$lfc<- log2(df$DKO/df$WT)

ggscatter(df,x="WT",y="lfc",color="DJ", size=0.2, alpha=0.1, palette = mypal) + coord_cartesian(xlim=c(0,200))
```
```{r fig.width=3, fig.height=3, error=F,echo=F,prompt=F,warning=F}
mypal <-c("#FF5050","#DD5050","#AA5050","#775050","#505050")

df$quantile <- as.numeric(quantcut(df$WT,5,na.rm = T))

ggviolin(df,x="quantile",y="lfc", add="median", fill="quantile", palette = mypal) + coord_cartesian(ylim = c(-5,5))
ggsave("plots/violin_G4_DKOlfc_by_WT_quantile.pdf")
```

```{r}
table(df$quantile,df$DJ)
```

