---
title: "G4 CUT&Tag analysis mESC (WT, FANCJ KO, DHX36 KO, DKO)"
output: html_notebook
---

Simon Elsässer, Karolinska Institutet (2023)

### DESeq2 analysis of peak universe (joint peak set called in any condition, must be called in all three replicates, MACS3)


```{r fig.width=6, fig.height=3}
bw_dir <- "/Volumes/DATA/DATA/Puck/bigwig/"
chromhmm <- "../genome/ESC_10_segments.mm39.bed"

library("wigglescout")
library("ggpubr")
library("ggplot2")
library("DESeq2")
library("dplyr")
library("ggrastr")

clean <- function (fn) {
  fn <- gsub(pattern = ".+/", "", x = fn)
  fn <- gsub(pattern = ".mm9.+", "", x = fn)
  fn <- gsub(pattern = ".mm39.+", "", x = fn)
  fn <- gsub(pattern = "_S.+", "", x = fn)
  fn <- gsub(pattern = ".scaled.bw", "", x = fn)
  fn <- gsub(pattern = ".unscaled.bw", "", x = fn)
  fn <- gsub(pattern = "_batch2", "", x = fn)
  fn <- gsub(pattern = "-", " ", x = fn)
  fn <- gsub(pattern = "_", " ", x = fn)
  fn <- gsub(pattern = " HA ", " ", x = fn)
  fn <- gsub(pattern = "D1D6", "FANCJ-/-", x = fn)
  fn <- gsub(pattern = "P2D2", "DHX36-/-", x = fn)
  fn <- gsub(pattern = "P3D4", "FANCJ-/-DHX36-/-", x = fn)
  return(fn)
}

BWs <- paste0(bw_dir,list.files(bw_dir,pattern="G4_.+combined.bw"))

mypal <-c("cornflowerblue","orange","red2","#505050")
mypal2 <- rep(mypal,each=2)
mypal3 <-c("cornflowerblue","cornflowerblue","cornflowerblue","orange","orange","orange","red2","red2","red2","505050","505050","505050")
```

```{r}
bw_granges_diff_analysis <- function(granges_c1,
                                     granges_c2,
                                     label_c1,
                                     label_c2,
                                     estimate_size_factors = FALSE,
                                     as_granges = FALSE) {

  # Bind first, get numbers after
  names_values <- NULL
  fields <- names(mcols(granges_c1))

  if ("name" %in% fields) {
    names_values <- mcols(granges_c1)[["name"]]
    granges_c1 <- granges_c1[, fields[fields != "name"]]
  }

  fields <- names(mcols(granges_c2))
  if ("name" %in% fields) {
    granges_c2 <- granges_c2[, fields[fields != "name"]]
  }

  cts_df <- cbind(data.frame(granges_c1), mcols(granges_c2))

  if (! is.null(names_values)) {
    rownames(cts_df) <- names_values
  }

  # Needs to drop non-complete cases and match rows
  complete <- complete.cases(cts_df)
  cts_df <- cts_df[complete, ]

  values_df <- cts_df[, 6:ncol(cts_df)] %>% dplyr::select(where(is.numeric))
  cts <- get_nreads_columns(values_df)

  condition_labels <- c(rep(label_c1, length(mcols(granges_c1))),
                        rep(label_c2, length(mcols(granges_c2))))


  coldata <- data.frame(colnames(cts), condition = as.factor(condition_labels))

  dds <- DESeq2::DESeqDataSetFromMatrix(countData = cts,
                                colData = coldata,
                                design = ~ condition,
                                rowRanges = granges_c1[complete, ])


  if (estimate_size_factors == TRUE) {
    dds <- DESeq2::estimateSizeFactors(dds)
  }
  else {
    # Since files are scaled, we do not want to estimate size factors
    sizeFactors(dds) <- c(rep(1, ncol(cts)))
  }

  dds <- DESeq2::estimateDispersions(dds)
  dds <- DESeq2::nbinomWaldTest(dds)

  if (as_granges) {
    result <- DESeq2::results(dds, format = "GRanges",alpha = 0.01)
    if (!is.null(names_values)) {
      result$name <- names_values[complete]
    }

  }
  else {
    # result <- results(dds, format="DataFrame")
    result <- dds
  }

  result
}

get_nreads_columns <- function(df, length_factor = 100) {
  # Convert mean coverages to round integer read numbers
  cts <- as.matrix(df)
  cts <- as.matrix(cts[complete.cases(cts),])
  cts <- round(cts*length_factor)
  cts
}
```


```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
bw_dir <- "/Volumes/DATA/DATA/Puck/bigwig//"
BWs_Rloop <- paste0(bw_dir,list.files(bw_dir,pattern="Rloop_.+_combined.bw"))
plot_profile_biv_genes_Rloop <- plot_bw_profile(bwfiles = BWs_Rloop,loci = "../genome/K27_bivalent_genes.mm39.bed", mode="stretch", labels = clean(BWs_Rloop),show_error=T,colors = mypal, verbose=F, remove_top=0.001) + scale_y_continuous(limits=c(0,20))
plot_profile_biv_genes_Rloop
```

```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
bw_dir <- "/Volumes/DATA/DATA/Puck/bigwig//"
BWs_Rloop <- paste0(bw_dir,list.files(bw_dir,pattern="Rloop_.+_R..bw"))
plot_profile_biv_genes_Rloop_DKO <- plot_bw_profile(bwfiles = BWs_Rloop,loci = "../genome/K27_bivalent_genes.mm39.bed", mode="stretch", labels = clean(BWs_Rloop),show_error=T,colors = mypal2, verbose=F, remove_top=0.001) + scale_y_continuous(limits=c(0,20))
plot_profile_biv_genes_Rloop_DKO 
```

```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
bw_dir <- "/Volumes/DATA/DATA/Puck/bigwig//"
BWs_Rloop <- paste0(bw_dir,list.files(bw_dir,pattern="Rloop_.+_combined.bw"))
plot_profile_hi_genes_Rloop_DKO <- plot_bw_profile(bwfiles = BWs_Rloop,loci = "../genome/genes_hi_lt10kb.mm39.bed", mode="stretch", labels = clean(BWs_Rloop),show_error=T,colors = mypal, verbose=F, remove_top=0.001) + scale_y_continuous(limits=c(0,25))
plot_profile_hi_genes_Rloop_DKO 
```
```{r fig.width=7, fig.height=4, error=F,echo=F,prompt=F,warning=F}
plot_bw_loci_summary_heatmap(BWs_Rloop,loci = "../genome/ChromHMM17.chr9.mm39lift.bed", remove_top = 0.01)
```
```{r fig.width=7, fig.height=4, error=F,echo=F,prompt=F,warning=F}
plot_bw_loci_summary_heatmap(BWs,loci = "../genome/ChromHMM17.chr9.mm39lift.bed", remove_top = 0.01)
```

```{r fig.width=4, fig.height=4, error=F,echo=F,prompt=F,warning=F}
bw_dir <- "/Volumes/DATA/DATA/Puck/bigwig//"
BWs_Rloop <- paste0(bw_dir,list.files(bw_dir,pattern="Rloop_.+_combined.bw"))
plot_profile_lo_genes_Rloop_DKO <- plot_bw_profile(bwfiles = BWs_Rloop,loci = "../genome/genes_lo_lt10kb.mm39.bed", mode="stretch", labels = clean(BWs_Rloop),show_error=T,colors = mypal, verbose=F, remove_top=0.001) + scale_y_continuous(limits=c(0,25))
plot_profile_lo_genes_Rloop_DKO 
```
```{r}
BWs_Rloop <- paste0(bw_dir,list.files(bw_dir,pattern="Rloop_.+_R..bw"))
gencode <- "../genome/gencode.vm33.mm39.bed"
gencode <- "../genome/genes_lo_mid_hi_bi.mm39.bed"

BWs.WT <- BWs_Rloop[grep("WT",BWs_Rloop)]
BWs.FANCJ <- BWs_Rloop[grep("D1D6",BWs_Rloop)]
BWs.DHX36 <- BWs_Rloop[grep("P2D2",BWs_Rloop)]
BWs.DKO <- BWs_Rloop[grep("P3D4",BWs_Rloop)]
  
# Calculate here some loci or bins
cov.WT <- bw_loci(BWs.WT, loci = gencode)
cov.DHX36 <- bw_loci(BWs.DHX36, loci = gencode)
cov.FANCJ <- bw_loci(BWs.FANCJ, loci = gencode)
cov.DKO <- bw_loci(BWs.DKO, loci = gencode)
```

```{r}
diff_DHX36 <- bw_granges_diff_analysis(cov.WT, cov.DHX36,
                                     "WT", "DHX36KO")
diff_FANCJ <- bw_granges_diff_analysis(cov.WT, cov.FANCJ,
                                     "WT", "FANCJ")
diff_DKO <- bw_granges_diff_analysis(cov.WT, cov.DKO,
                                     "WT", "DKO")


# This takes care of low conts and things like this, but you can also use
# diff_results as is for the things below
lfc_DHX36 <- DESeq2::lfcShrink(diff_DHX36, coef = "condition_WT_vs_DHX36KO", type="apeglm")
lfc_FANCJ <- DESeq2::lfcShrink(diff_FANCJ, coef = "condition_WT_vs_FANCJ", type="apeglm")
lfc_DKO <- DESeq2::lfcShrink(diff_DKO, coef = "condition_WT_vs_DKO", type="apeglm")

data_DHX36 <- plotMA(lfc_DHX36, returnData = T)
data_DHX36$lfc <- -data_DHX36$lfc
data_DHX36$mean <- log10(data_DHX36$mean)

data_FANCJ <- plotMA(lfc_FANCJ, returnData = T)
data_FANCJ$lfc <- -data_FANCJ$lfc
data_FANCJ$mean <- log10(data_FANCJ$mean)

data_DKO <- plotMA(lfc_DKO, returnData = T)
data_DKO$lfc <- -data_DKO$lfc
data_DKO$mean <- log10(data_DKO$mean)
```


```{r fig.width=2, fig.height=2}
ggscatter(data_DHX36,x ="mean",y="lfc",color="isDE",size = 0.8, alpha=0.5, palette = c("gray",mypal[1])) + geom_hline(yintercept = 0, linetype="dashed", size=0.1) + coord_cartesian(ylim=c(-5,5))
plot_MA_DHX36 <- rasterize(last_plot(), layers='Point', dpi=600) 
```
```{r fig.width=2, fig.height=2}
data_DHX36$cov.WT <- rowMeans(as.data.frame(cov.WT)[,6:7])
data_DHX36$cov.DHX36 <- rowMeans(as.data.frame(cov.DHX36)[,6:7])
ggscatter(data_DHX36,x ="cov.WT",y="cov.DHX36",color="isDE",size = 0.8, alpha=0.5, palette = c("gray",mypal[1])) + scale_x_continuous(trans="log",limits = c(0.5,400)) + scale_y_continuous(trans="log",limits = c(0.5,400)) + geom_abline(slope = 1, linetype="dashed", size=0.1)
plot_XY_DHX36 <- rasterize(last_plot(), layers='Point', dpi=600) 
```
```{r fig.width=2, fig.height=2}
data_DHX36$cov.WT <- rowMeans(as.data.frame(cov.WT)[,6:7])
data_DHX36$cov.DHX36 <- rowMeans(as.data.frame(cov.DHX36)[,6:7])
ggscatter(data_DHX36,x ="cov.WT",y="cov.DHX36",color="isDE",size = 0.8, alpha=0.5, palette = c("gray",mypal[1])) + scale_x_continuous(limits = c(-10,50)) + scale_y_continuous(limits = c(-10,50)) + geom_abline(slope = 1, linetype="dashed", size=0.1)
plot_XY_DHX36_zoom <- rasterize(last_plot(), layers='Point', dpi=600) 
```

```{r fig.width=2, fig.height=2}
ggscatter(data_FANCJ,x ="mean",y="lfc",color="isDE",size = 0.8, alpha=0.5, palette = c("gray",mypal[2])) + geom_hline(yintercept = 0, linetype="dashed", size=0.1) + coord_cartesian(ylim=c(-5,5))
plot_MA_FANCJ <- rasterize(last_plot(), layers='Point', dpi=600) 
```

```{r fig.width=2, fig.height=2}
data_FANCJ$cov.WT <- rowMeans(as.data.frame(cov.WT)[,6:7])
data_FANCJ$cov.FANCJ <- rowMeans(as.data.frame(cov.FANCJ)[,6:7])
ggscatter(data_FANCJ,x ="cov.WT",y="cov.FANCJ",color="isDE",size = 0.8, alpha=0.5, palette = c("gray",mypal[2])) + geom_hline(yintercept = 0, linetype="dashed", size=0.1) + scale_x_continuous(trans="log",limits = c(0.5,400)) + scale_y_continuous(trans="log",limits = c(0.5,400)) + geom_abline(slope = 1, linetype="dashed", size=0.1)
plot_XY_FANCJ <- rasterize(last_plot(), layers='Point', dpi=600) 
```

```{r fig.width=2, fig.height=2}
ggscatter(data_DKO,x ="mean",y="lfc",color="isDE",size = 0.8, alpha=0.5, palette = c("gray",mypal[3])) + geom_hline(yintercept = 0, linetype="dashed", size=0.1) + coord_cartesian(ylim=c(-5,5))
plot_MA_DKO <- rasterize(last_plot(), layers='Point', dpi=600) 
```

```{r fig.width=2, fig.height=2}
data_DKO$cov.WT <- rowMeans(as.data.frame(cov.WT)[,6:7])
data_DKO$cov.DKO <- rowMeans(as.data.frame(cov.DKO)[,6:7])
ggscatter(data_DKO,x ="cov.WT",y="cov.DKO",color="isDE",size = 0.8, alpha=0.5, palette = c("gray",mypal[3])) + geom_hline(yintercept = 0, linetype="dashed", size=0.1) + scale_x_continuous(trans="log",limits = c(0.5,400)) + scale_y_continuous(trans="log",limits = c(0.5,400)) + geom_abline(slope = 1, linetype="dashed", size=0.1)
plot_XY_DKO <- rasterize(last_plot(), layers='Point', dpi=600) 
```

```{r fig.width=2, fig.height=2}
data_DKO$lfc_DHX36 <- data_DHX36$lfc
data_DKO$lfc_FANCJ <- data_FANCJ$lfc
ggscatter(data_DKO,x ="lfc_DHX36",y="lfc",color="isDE",size = 0.8, alpha=0.5, palette = c("gray",mypal[3]))+ geom_hline(yintercept = 0, linetype="dashed", size=0.1) + geom_vline(xintercept = 0, linetype="dashed", size=0.1) + coord_cartesian(ylim=c(-5,5), xlim=c(-5,5))
plot_LFC_DKO_vs_DHX36 <- rasterize(last_plot(), layers='Point', dpi=600)
```
```{r fig.width=2, fig.height=2}
ggscatter(data_DKO,x ="lfc_FANCJ",y="lfc",color="isDE",size = 0.8, alpha=0.5, palette = c("gray",mypal[3]))+ geom_hline(yintercept = 0, linetype="dashed", size=0.1) + geom_vline(xintercept = 0, linetype="dashed", size=0.1) + coord_cartesian(ylim=c(-5,5), xlim=c(-5,5))
plot_LFC_DKO_vs_FANCJ <- rasterize(last_plot(), layers='Point', dpi=600)
```
```{r fig.width=2, fig.height=2}
data_DHX36$lfc_DKO <- data_DKO$lfc
ggscatter(data_DHX36,x ="lfc",y="lfc_DKO",color="isDE",size = 0.8, alpha=0.5, palette = c("gray",mypal[1]))+ geom_hline(yintercept = 0, linetype="dashed", size=0.1) + geom_vline(xintercept = 0, linetype="dashed", size=0.1) + coord_cartesian(ylim=c(-5,5), xlim=c(-5,5))
```


```{r}
cov <- cbind( as.data.frame(cov.WT)[,1:7], 
              as.data.frame(cov.DHX36)[,6:7], 
              as.data.frame(cov.FANCJ)[,6:7], 
              as.data.frame(cov.DKO)[,6:7])

colnames(cov) <- c(colnames(cov)[1:5],"WT1","WT2","DHX1","DHX2","FAN1","FAN2","DKO1","DKO2")
```

```{r fig.height=2, fig.width=3}
library(reshape2)
mdf <- melt(data.frame(name=cov.WT$name,cov[,6:13]))
mdf <- mdf[mdf$value<500,]
mdf$cond <- "WT"
mdf$cond[grep("DHX",mdf$variable)] <- "DHX36-/-"
mdf$cond[grep("FAN",mdf$variable)] <- "FANCJ-/-"
mdf$cond[grep("DKO",mdf$variable)] <- "DHX36-/-FANCJ-/-"
plot_viol_rep_all_peaks <- ggviolin(mdf, x="variable",y="value",fill="cond",palette = mypal, add="mean_sd") +
  coord_cartesian(ylim=c(0,10))
plot_viol_rep_all_peaks
```

```{r fig.height=2, fig.width=3}
plot_viol_rep_hi_genes <- ggviolin(mdf[mdf$name=="gene_hi",], x="variable",y="value",fill="cond",palette = mypal, add="mean_sd") +
  coord_cartesian(ylim=c(0,10))
plot_viol_rep_hi_genes
```
```{r fig.height=2, fig.width=3}
plot_viol_rep_biv_genes <- ggviolin(mdf[mdf$name=="gene_bi",], x="variable",y="value",fill="cond",palette = mypal, add="mean_sd") +
  coord_cartesian(ylim=c(0,10))
plot_viol_rep_biv_genes
```
```{r fig.height=2, fig.width=3}
plot_viol_rep_by_genes <- ggviolin(mdf, x="name",y="value",fill="cond",palette = mypal, add="mean_sd") +
  coord_cartesian(ylim=c(0,10))
plot_viol_rep_by_genes
```
