---
title: "G4 CUT&Tag analysis mESC (WT, FANCJ KO, DHX36 KO, DKO)"
output: html_notebook
---

Simon Elsässer, Karolinska Institutet (2023)

### Plots of differentially expressed genes from RNA-seq


```{r fig.width=6, fig.height=3}
bw_dir <- "/Volumes/DATA/DATA/Puck/bigwig/"
chromhmm <- "../genome/ESC_10_segments.mm39.bed"

library("wigglescout")
library("ggpubr")
library("ggplot2")
library("DESeq2")
library("dplyr")
library("ggrastr")

clean <- function (fn) {
  fn <- gsub(pattern = ".+/", "", x = fn)
  fn <- gsub(pattern = ".mm9.+", "", x = fn)
  fn <- gsub(pattern = ".mm39.+", "", x = fn)
  fn <- gsub(pattern = "_S.+", "", x = fn)
  fn <- gsub(pattern = ".scaled.bw", "", x = fn)
  fn <- gsub(pattern = ".unscaled.bw", "", x = fn)
  fn <- gsub(pattern = "_batch2", "", x = fn)
  fn <- gsub(pattern = "-", " ", x = fn)
  fn <- gsub(pattern = "_", " ", x = fn)
  fn <- gsub(pattern = " HA ", " ", x = fn)
  fn <- gsub(pattern = "D1D6", "FANCJ-/-", x = fn)
  fn <- gsub(pattern = "P2D2", "DHX36-/-", x = fn)
  fn <- gsub(pattern = "P3D4", "FANCJ-/-DHX36-/-", x = fn)
  return(fn)
}

BWs <- paste0(bw_dir,list.files(bw_dir,pattern="G4_.+_combined.bw"))
Rloop <- paste0(bw_dir,list.files(bw_dir,pattern="Rloop_.+_combined.bw"))

mypal <-c("cornflowerblue","orange","red2","#505050")
mypal3 <-c("cornflowerblue","cornflowerblue","cornflowerblue","orange","orange","orange","red2","red","red2","black","black","black")
mypal2 <-c("cornflowerblue","cornflowerblue","orange","orange","red2","red","black","black")
```

```{r fig.width=3, fig.height=3, error=F,echo=F,prompt=F,warning=F}
plot_profile_RNAseq_DKO_spec <- plot_bw_profile(bwfiles = BWs,loci = "../genelists//lncRNA_DKOspec.bed", mode="stretch", labels = clean(BWs),show_error=T,colors = mypal, verbose=F, remove_top=0.01) + scale_y_continuous(limits=c(0,40))
plot_profile_RNAseq_DKO_spec
```

```{r fig.width=3, fig.height=3, error=F,echo=F,prompt=F,warning=F}
plot_profile_RNAseq_common <- plot_bw_profile(bwfiles = BWs,loci = "../genelists//lncRNA_common.bed", mode="stretch", labels = clean(BWs),show_error=T,colors = mypal, verbose=F, remove_top=0.01) + scale_y_continuous(limits=c(0,50))
plot_profile_RNAseq_common
```

```{r fig.width=3, fig.height=3, error=F,echo=F,prompt=F,warning=F}
plot_profile_RNAseq_DKO_up <- plot_bw_profile(bwfiles = BWs,loci = "../genelists//lncRNA_DKOup.bed", mode="stretch", labels = clean(BWs),show_error=T,colors = mypal, verbose=F, remove_top=0.01) + scale_y_continuous(limits=c(0,40))
plot_profile_RNAseq_DKO_up
```
```{r fig.width=3, fig.height=3, error=F,echo=F,prompt=F,warning=F}
plot_profile_RNAseq_WT_spec <- plot_bw_profile(bwfiles = BWs,loci = "../genelists//lncRNA_WTspec.bed", mode="stretch", labels = clean(BWs),show_error=T,colors = mypal, verbose=F, remove_top=0.01) + scale_y_continuous(limits=c(0,40))
plot_profile_RNAseq_WT_spec
```


```{r fig.width=3, fig.height=3, error=F,echo=F,prompt=F,warning=F}
plot_profile_RNAseq_DKO_spec <- plot_bw_profile(bwfiles = Rloop,loci = "../genelists//lncRNA_DKOspec.bed", mode="stretch", labels = clean(Rloop),show_error=T,colors = mypal, verbose=F, remove_top=0.01) + scale_y_continuous(limits=c(0,15))
plot_profile_RNAseq_DKO_spec
```
```{r fig.width=3, fig.height=3, error=F,echo=F,prompt=F,warning=F}
plot_profile_RNAseq_common <- plot_bw_profile(bwfiles = Rloop,loci = "../genelists//lncRNA_common.bed", mode="stretch", labels = clean(Rloop),show_error=T,colors = mypal, verbose=F, remove_top=0.01) + scale_y_continuous(limits=c(0,20))
plot_profile_RNAseq_common
```
```{r fig.width=3, fig.height=3, error=F,echo=F,prompt=F,warning=F}
plot_profile_RNAseq_DKOup <- plot_bw_profile(bwfiles = Rloop,loci = "../genelists//lncRNA_DKOup.bed", mode="stretch", labels = clean(Rloop),show_error=T,colors = mypal, verbose=F, remove_top=0.01) + scale_y_continuous(limits=c(0,20))
plot_profile_RNAseq_DKOup
```

```{r fig.width=3, fig.height=3, error=F,echo=F,prompt=F,warning=F}
plot_profile_RNAseq_WT_spec <- plot_bw_profile(bwfiles = Rloop,loci = "../genelists//lncRNA_WTspec.bed", mode="stretch", labels = clean(Rloop),show_error=T,colors = mypal, verbose=F, remove_top=0.01) + scale_y_continuous(limits=c(0,20))
plot_profile_RNAseq_WT_spec
```